// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yreltrccpkraxsbmwlyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyZWx0cmNjcGtyYXhzYm13bHlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNTI4NTYsImV4cCI6MjA2MzYyODg1Nn0.Oiws7jLFSDNbpiWXIilDBucJhJ8kwxm14fhpO_EhBDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);